apiVersion: apps/v1
kind: Deployment
metadata:
  name: blobstorageservice-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blobstorageservice-backend
  template:
    metadata:
      labels:
        app: blobstorageservice-backend
    spec:
      containers:
        - name: blobstorageservice-backend
          image: rikhendrix/blobstorageservice-backend:latest
          ports:
            - containerPort: 5099
          env:
            - name: BLOB_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: blob-storage-secret
                  key: connection-string
            - name: VIRUSTOTAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: virus-total-secret
                  key: api-key
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
