apiVersion: v1
kind: Service
metadata:
  name: blobstorageservice-backend
spec:
  selector:
    app: blobstorageservice-backend
  ports:
    - protocol: TCP
      port: 5099
      targetPort: 5099
  type: ClusterIP
