apiVersion: v1
kind: Service
metadata:
  name: blobstorageservice-backend
spec:
  selector:
    app: blobstorageservice-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
